In [1]:
# import numpy
import numpy as np

## Array types and conversions between types.

In [2]:
integers = np.array([10, 20, 30, 40, 50])
integers

array([10, 20, 30, 40, 50])

In [3]:
integers[0]

10

In [4]:
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [5]:
# all element must be intergers 
integers[0]=20.6
integers

array([20, 20, 30, 40, 50])

In [6]:
integers.dtype

dtype('int32')

In [7]:
# all floats 
floats = np.array([1.2, 2.3, 4.5, 6.8])
floats

array([1.2, 2.3, 4.5, 6.8])

In [8]:
floats[0] = 1
floats

array([1. , 2.3, 4.5, 6.8])

## Multidimensional arrays

In [9]:
#matrix 
nums= np.array([[0, 1, 2, 3, 5], [6, 7, 8, 9, 10]])
nums

array([[ 0,  1,  2,  3,  5],
       [ 6,  7,  8,  9, 10]])

In [10]:
# first element 
nums[0,0]

0

In [11]:
#last element 
nums[1,4]

10

In [12]:
# to find how manay dimenstion 
nums.ndim

2

In [13]:
multiDim = np.array([[[0, 1, 2, 3, 5], [6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
multiDim

array([[[ 0,  1,  2,  3,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [14]:
multiDim.ndim

3

In [15]:
# print 12 
multiDim[1, 0, 1]

12

## Creating arrays from lists and other Python structures

In [16]:
first_list = [1, 2, 3, 4, 5, 6]
first_list

[1, 2, 3, 4, 5, 6]

In [17]:
first_array = np.array(first_list)
first_array

array([1, 2, 3, 4, 5, 6])

In [18]:
second_list = [1, 2, 3, -1.25, 1200.356, 4]
second_array = np.array(second_list)
second_array

array([ 1.000000e+00,  2.000000e+00,  3.000000e+00, -1.250000e+00,
        1.200356e+03,  4.000000e+00])

In [19]:
third_list = [111, 'Home', 125, 'Sky']
third_array = np.array(third_list)
third_array

array(['111', 'Home', '125', 'Sky'], dtype='<U11')

In [20]:
first_tuple= (5, 10, 12, 9, 7)
first_tuple

(5, 10, 12, 9, 7)

In [21]:
tuple2array = np.array(first_tuple)
tuple2array

array([ 5, 10, 12,  9,  7])

## Intrinsic NumPy array creation

<h3 style="color:red">intergers array</h3>

In [22]:
integers_array1 = np.arange(10)
print('First integers array: ', integers_array1)
integers_array2 = np.arange(10, 30, 2)
print('Second integers array: ', integers_array2)

First integers array:  [0 1 2 3 4 5 6 7 8 9]
Second integers array:  [10 12 14 16 18 20 22 24 26 28]


<h3 style="color:red">floats array</h3> 

In [23]:
float_array1 = np.linspace(10, 20)
print('First float array: ', float_array1)
float_array2 = np.linspace(10, 20, 5)
print('Second integers array: ', float_array2)

First float array:  [10.         10.20408163 10.40816327 10.6122449  10.81632653 11.02040816
 11.2244898  11.42857143 11.63265306 11.83673469 12.04081633 12.24489796
 12.44897959 12.65306122 12.85714286 13.06122449 13.26530612 13.46938776
 13.67346939 13.87755102 14.08163265 14.28571429 14.48979592 14.69387755
 14.89795918 15.10204082 15.30612245 15.51020408 15.71428571 15.91836735
 16.12244898 16.32653061 16.53061224 16.73469388 16.93877551 17.14285714
 17.34693878 17.55102041 17.75510204 17.95918367 18.16326531 18.36734694
 18.57142857 18.7755102  18.97959184 19.18367347 19.3877551  19.59183673
 19.79591837 20.        ]
Second integers array:  [10.  12.5 15.  17.5 20. ]


<h3 style="color:red">random array</h3>   

In [24]:
rand_array1 = np.random.rand(10) #float 
print("Float random array : " , rand_array1)
rand_array2 = np.random.randint(10, 30, 9)
print("Integer random array :" , rand_array2)

Float random array :  [0.95868817 0.03886153 0.05156292 0.85307048 0.01393066 0.89325176
 0.48389759 0.8113543  0.48004286 0.78712987]
Integer random array : [28 10 29 10 22 22 15 21 14]


## Creating arrays filled with constant values

<h3 style="color:red">Zero array</h3>   

In [25]:
z_array1 = np.zeros(5)
z_array1

array([0., 0., 0., 0., 0.])

In [26]:
z_array2 = np.zeros((4,5), dtype=int) # 4 rows, 5 columns 
z_array2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

<h3 style="color:red">Ones array</h3>   

In [27]:
o_array1 = np.ones(6)
o_array1

array([1., 1., 1., 1., 1., 1.])

In [28]:
o_array2 = np.ones((7,8), dtype=int) # 7 rows, 8 columns
o_array2

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])

<h3 style="color:red">Full array</h3>   

In [29]:
f_array1 = np.empty(10, dtype=int)
f_array1.fill(12)
f_array1

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [30]:
f_array2 = np.full(5, 10) # 5 columns
f_array2

array([10, 10, 10, 10, 10])

In [31]:
f_array3 = np.full((4,5) , 8) # 4 rows, 5 columns with 8 number
f_array3

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

## Finding the shape and size of an array

In [32]:
np.shape(f_array1)

(10,)

In [33]:
np.shape(f_array2)

(5,)

In [34]:
np.shape(f_array3)

(4, 5)

In [35]:
np.shape(o_array2)

(7, 8)