In [1]:
# import numpy
import numpy as np

### Array types and conversions between types.

In [4]:
integers = np.array([10, 20, 30, 40, 50])
integers

array([10, 20, 30, 40, 50])

In [5]:
integers[0]

10

In [7]:
integers[0]=20
integers

array([20, 20, 30, 40, 50])

In [8]:
# all element must be intergers 
integers[0]=20.6
integers

array([20, 20, 30, 40, 50])

In [9]:
integers.dtype

dtype('int32')

In [11]:
# all floats 
floats = np.array([1.2, 2.3, 4.5, 6.8])
floats

array([1.2, 2.3, 4.5, 6.8])

In [12]:
floats[0] = 1
floats

array([1. , 2.3, 4.5, 6.8])

### Multidimensional arrays

In [20]:
#matrix 
nums= np.array([[0, 1, 2, 3, 5], [6, 7, 8, 9, 10]])
nums

array([[ 0,  1,  2,  3,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
# first element 
nums[0,0]

0

In [23]:
#last element 
nums[1,4]

10

In [24]:
# to find how manay dimenstion 
nums.ndim

2

In [30]:
multiDim = np.array([[[0, 1, 2, 3, 5], [6, 7, 8, 9, 10]],[[11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]])
multiDim

array([[[ 0,  1,  2,  3,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [31]:
multiDim.ndim

3

In [32]:
# print 12 
multiDim[1, 0, 1]

12

### Creating arrays from lists and other Python structures

In [34]:
first_list = [1, 2, 3, 4, 5, 6]
first_list

[1, 2, 3, 4, 5, 6]

In [36]:
first_array = np.array(first_list)
first_array

array([1, 2, 3, 4, 5, 6])

In [40]:
second_list = [1, 2, 3, -1.25, 1200.356, 4]
second_array = np.array(second_list)
second_array

array([ 1.000000e+00,  2.000000e+00,  3.000000e+00, -1.250000e+00,
        1.200356e+03,  4.000000e+00])

In [41]:
third_list = [111, 'Home', 125, 'Sky']
third_array = np.array(third_list)
third_array

array(['111', 'Home', '125', 'Sky'], dtype='<U11')

In [42]:
first_tuple= (5, 10, 12, 9, 7)
first_tuple

(5, 10, 12, 9, 7)

In [44]:
tuple2array = np.array(first_tuple)
tuple2array

array([ 5, 10, 12,  9,  7])

### Intrinsic NumPy array creation