## Adding, removing, and sorting elements

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1, 2, 3, 5])
arr1

array([1, 2, 3, 5])

<h3 style="color:blue">insert</h3>

In [18]:
## arg 1 : array name.
## arg 2 : the index 
## arg 3 : the number 

print(arr1)
arr1_1 = np.insert(arr1, 1,4) 
arr1_1

[1 2 3 5]


array([1, 4, 2, 3, 5])

<h3 style="color:blue">append</h3>

In [19]:
## arg 1 : array name.
## arg 2 : the number 

print(arr1)
arr1_2 = np.append(arr1, 5)
arr1_2

[1 2 3 5]


array([1, 2, 3, 5, 5])

<h3 style="color:blue">delete</h3>

In [21]:
## arg 1 : array name.
## arg 2 : the index  

print(arr1)
arr1_3 = np.delete(arr1, 2)
arr1_3

[1 2 3 5]


array([1, 2, 5])

<h3 style="color:blue">sort</h3>

In [22]:
print(np.sort(arr1_1))

[1 2 3 4 5]


In [25]:
arr2 = np.array([[3, 2, 5, 7, 4], [5, 0, 8, 3, 1]])
arr2

array([[3, 2, 5, 7, 4],
       [5, 0, 8, 3, 1]])

In [26]:
print(np.sort(arr2))

[[2 3 4 5 7]
 [0 1 3 5 8]]


## Copies and views

In [27]:
students_ids_number=np.array([1111 ,1212 ,1313 ,1414 ,1515 ,1616 ,1717 ,1818])
students_ids_number

array([1111, 1212, 1313, 1414, 1515, 1616, 1717, 1818])

In [28]:
students_ids_number_reg=students_ids_number
print("id of students_ids_number",id(students_ids_number))
print("id of students_ids_number_reg",id(students_ids_number_reg))

id of students_ids_number 1921252117744
id of students_ids_number_reg 1921252117744


In [30]:
## when I change in first array the second array will change
students_ids_number_reg[1]=2222
print(students_ids_number)
print(students_ids_number_reg)

[1111 2222 1313 1414 1515 1616 1717 1818]
[1111 2222 1313 1414 1515 1616 1717 1818]


<h3 style="color:blue">copy</h3>

In [32]:
students_ids_number_cp=students_ids_number.copy()
students_ids_number_cp

array([1111, 2222, 1313, 1414, 1515, 1616, 1717, 1818])

In [34]:
## only the changes happened in copy array 
students_ids_number[0]=1000
print ("original: ", students_ids_number)
print("copy: ",students_ids_number_cp)

original:  [1000 2222 1313 1414 1515 1616 1717 1818]
copy:  [1111 2222 1313 1414 1515 1616 1717 1818]


<h3 style="color:blue">view</h3>

In [35]:
students_ids_number_v=students_ids_number.view()
students_ids_number_v

array([1000, 2222, 1313, 1414, 1515, 1616, 1717, 1818])

In [37]:
## the changes happened in both arraies 
students_ids_number_v[0]=2000
print("original: ", students_ids_number)
print("view:",students_ids_number_v)

original:  [2000 2222 1313 1414 1515 1616 1717 1818]
view: [2000 2222 1313 1414 1515 1616 1717 1818]


In [38]:
print(students_ids_number_cp.base)
print(students_ids_number_v.base)

None
[2000 2222 1313 1414 1515 1616 1717 1818]


## Reshaping arrays

In [39]:
arr=np.arange(1,13)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [42]:
arr_2=np.reshape(arr,(3,4))  ## 3 rows, 4 columns 
arr_2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr_3=np.reshape(arr,(4,4)) 

ValueError: cannot reshape array of size 12 into shape (4,4)

In [45]:
arr_4 = np.reshape(arr,(3,2,2))
print(arr_4)
print("Dimensions of fifth_arr is ",arr_4.ndim)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Dimensions of fifth_arr is  3


<h3 style="color:blue">Flat (line array)</h3>

In [47]:
arr_5 = np.reshape(arr_4,-1)
arr_5

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [52]:
arr_flat = arr_4.flatten()
print("arr_flat:",arr_6)
arr_rav = arr_4.ravel()
print("arr_rav:",arr_7)

arr_flat: [100   2   3   4   5   6   7   8   9  10  11  12]
arr_rav: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [53]:
arr_flat [0] =100
arr_flat

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [54]:
arr_rav[0] = 100
arr_rav

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

## Indexing and slicing

In [55]:
twodim_arr = np.reshape(np.arange(12),(3,4))
twodim_arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [56]:
twodim_arr[1]

array([4, 5, 6, 7])

In [57]:
twodim_arr[1,1]

5

In [59]:
threedim_arr = np.reshape(np.arange(3*4*5),(3,4,5))
threedim_arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [61]:
threedim_arr[0]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [69]:
threedim_arr[0 ,0:] 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [70]:
threedim_arr[0 ,0: , 3] 

array([ 3,  8, 13, 18])

In [64]:
threedim_arr[0,2:12,3]

array([13, 18])

## Joining and splitting ararys

In [71]:
first_arr=np.arange(1,11)
second_arr=np.arange(11,21)
print("first_arr",first_arr)
print("second_arr",second_arr)

first_arr [ 1  2  3  4  5  6  7  8  9 10]
second_arr [11 12 13 14 15 16 17 18 19 20]


In [72]:
con_arr=np.concatenate((first_arr,second_arr))
con_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [73]:
st_arr = np.stack((first_arr,second_arr))
st_arr 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [74]:
hst_arr=np.hstack((first_arr,second_arr))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [75]:
vst_arr=np.vstack((first_arr,second_arr))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])